# Generated by Django 4.2.27 on 2026-01-28 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel_type',
            field=models.CharField(choices=[('paylink', 'Paylink'), ('ussd', 'USSD')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
