# Generated by Django 4.2.27 on 2026-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_type',
            field=models.CharField(blank=True, choices=[('momo', 'Mobile Money'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
