# Generated by Django 4.2.27 on 2026-01-25 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paychannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentchannel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentchannel',
            name='ussd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
